#!/usr/bin/env bash
set -e

echo "Collecting statics"
python manage.py collectstatic --noinput

echo "Running migrations"
python manage.py migrate

gunicorn 'eterlast.wsgi' &

nginx -g 'daemon off;' > /dev/null