# Generated by Django 4.0.3 on 2022-04-09 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('creator_network', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('asset_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('picture', models.URLField()),
                ('external_link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('supply', models.IntegerField()),
                ('royalties', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.collection')),
            ],
        ),
    ]
