# Generated by Django 4.0.3 on 2022-04-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('creator_network', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='nft_pictures')),
                ('external_link', models.URLField()),
                ('description', models.TextField()),
                ('supply', models.IntegerField()),
                ('royalties', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.TextField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.collection')),
            ],
        ),
    ]
