# Generated by Django 4.0.3 on 2022-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='asset_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nft',
            name='buyer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.URLField(),
        ),
    ]
